import os
import logging
import asyncio
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, InputFile
from telegram.ext import Application, CommandHandler, MessageHandler, ContextTypes, filters

import aiohttp
from datetime import datetime

#######################
# CONFIGURACIÓN SEGURA
#######################
REQUIRED_ENV = [
    "TELEGRAM_TOKEN", "CEREBRO_API", "BACKEND_URL"
]
for key in REQUIRED_ENV:
    if not os.environ.get(key):
        raise EnvironmentError(f"Falta la variable de entorno: {key}")
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
CEREBRO_API = os.environ.get("CEREBRO_API")

logging.basicConfig(
    format="%(asctime)s %(levelname)s %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

#######################
# GESTIÓN DE USUARIOS Y PERMISOS
#######################
ADMIN_IDS = [int(x) for x in os.environ.get("ADMIN_IDS", "").split(",") if x]
user_sessions = {}

def is_admin(userid):
    return userid in ADMIN_IDS

#######################
# UTILS HTTP ASYNC
#######################
async def get_backend_data(endpoint):
    async with aiohttp.ClientSession() as session:
        async with session.get(f"{CEREBRO_API}/{endpoint}", timeout=10) as resp:
            if resp.status != 200:
                raise Exception(f"Error backend {endpoint}: {resp.status}")
            return await resp.json()

#######################
# COMANDOS
#######################
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    userid = update.effective_user.id
    user_sessions[userid] = {"activo": True, "inicio": datetime.now()}
    await update.message.reply_text("¡Bienvenido a CEREBRO AI! Usa /ayuda para ver comandos.")

async def ayuda(update: Update, context: ContextTypes.DEFAULT_TYPE):
    comandos = [
        "/productos - Lista productos",
        "/crear <nombre> - Crear producto",
        "/pedidos - Últimos pedidos",
        "/clientes - Estadísticas clientes",
        "/dashboard - Panel avanzado",
        "/ayuda - Ver comandos",
        "/status - Ver estado backend"
    ]
    await update.message.reply_text("🧠 *CEREBRO AI Comandos*\n" + "\n".join(comandos), parse_mode="Markdown")

async def productos(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Consultando productos...")
    try:
        productos = await get_backend_data("productos")
        respuesta = "\n".join([f"{p['nombre']} | {p['precio']}€ | Stock: {p['stock']}" for p in productos[:10]])
        await update.message.reply_text(f"*Productos:*\n{respuesta}", parse_mode="Markdown")
    except Exception as e:
        await update.message.reply_text(f"❌ Error al consultar productos: {e}")

# ... Implementa igual para pedidos, clientes, crear, etc ...

#######################
# COMANDO ESPECIAL DASHBOARD
#######################
async def dashboard(update: Update, context: ContextTypes.DEFAULT_TYPE):
    # Consulta varias APIs para generar panel unificado, genera gráfico y exporta CSV/PDF si admin
    await update.message.reply_text("Generando dashboard avanzado...")
    # Ejemplo: Simula estadística y envía archivo
    # await update.message.reply_document(InputFile("dashboard.csv"), caption="Dashboard CSV")

#######################
# HANDLER DE TEXTO NATURAL INTELIGENTE
#######################
async def texto(update: Update, context: ContextTypes.DEFAULT_TYPE):
    texto = update.message.text.lower()
    # Aplica fuzzy matching/nlp simple o llama a backend IA para entender el comando
    if "producto" in texto:
        await productos(update, context)
    elif "pedido" in texto:
        await pedidos(update, context)
    # ...

#######################
# HANDLER DE ERRORES GENERAL
#######################
async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE):
    logger.exception(f"Error: {context.error}")
    if isinstance(update, Update) and update.message:
        await update.message.reply_text("Ocurrió un error inesperado. Por favor, intenta de nuevo.")
    # Si es crítico y admin, envía log por Telegram

#######################
# MAIN
#######################
def main():
    app = Application.builder().token(TELEGRAM_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("ayuda", ayuda))
    app.add_handler(CommandHandler("productos", productos))
    app.add_handler(CommandHandler("dashboard", dashboard))
    # Otros comandos...
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, texto))
    app.add_error_handler(error_handler)
    logger.info("Bot listo")
    app.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()                                                                                                                                                                                                                                                                                                                "user_id": f"telegram_{user_id}"
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                        async with session.post(
                                                                                                                                                                                                                                                                                                                                                                                                        f"{CEREBRO_API}/execute",
                                                                                                                                                                                                                                                                                                                                                                                                                        json=payload,
                                                                                                                                                                                                                                                                                                                                                                                                                                        timeout=30
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) as resp:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if resp.status == 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data = await resp.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return data.get('mensaje') or data.get('message') or data.get('respuesta') or str(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error_text = await resp.text()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return f" Error {resp.status}: {error_text}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except asyncio.TimeoutError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "⏱ Timeout: El servidor tardó demasiado en responder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return f" Error de conexión: {str(e)}"


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def manejar_mensaje(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Maneja mensajes de texto normales"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user_id = update.effective_user.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        texto = update.message.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Indicador de que está procesando
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await update.message.reply_text(" Procesando...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Ejecutar comando
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                respuesta = await ejecutar_comando(texto, user_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Responder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await update.message.reply_text(respuesta)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Maneja errores"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f" Error: {context.error}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if update and update.message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await update.message.reply_text(f" Ocurrió un error: {context.error}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Inicia el bot"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(" Iniciando Cerebro AI Bot...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Crear aplicación
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app = Application.builder().token(TELEGRAM_TOKEN).build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Comandos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(CommandHandler("ayuda", ayuda))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.add_handler(CommandHandler("help", ayuda))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.add_handler(CommandHandler("productos", productos))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_handler(CommandHandler("crear", crear_producto))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(CommandHandler("pedidos", pedidos))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.add_handler(CommandHandler("status", status))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Mensajes de texto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, manejar_mensaje))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Procesar mensaje normal
99|        if text and not text.startswith('/'):
100|            logger.info(f" Procesando: {text}")
101|            
102|            # Llamar backend
103|            result = call_backend_agent(text, f"telegram_{chat_id}")
104|            
105|            if result['success']:
106|                mensaje = result.get('mensaje', 'Sin respuesta del backend')
107|                send_telegram_message(f" {mensaje}", chat_id)
108|                logger.info(" Enviado correctamente")
109|            else:
110|                error = result.get('error', 'Error desconocido')
111|                send_telegram_message(f" Error: {error}", chat_id)
112|                logger.error(f" Error: {error}")
113|        
114|        return jsonify({"ok": True})
115|        
116|    except Exception as e:
117|        logger.error(f" Error webhook: {e}")
118|        return jsonify({"ok": False, "error": str(e)}), 500
119|
120|if __name__ == "__main__":
121|    logger.info(" INICIANDO TELEGRAM BOT URGENTE")
122|    logger.info(f" Backend: {BACKEND_URL}")
123|    
124|    # Test inicial
125|    try:
126|        test_response = requests.get(f"https://ai-agent-backend80.onrender.com/api/agent/status", timeout=10)
127|        if test_response.status_code == 200:
128|            logger.info(" Backend verificado")
129|            send_telegram_message(" *Bot fix urgente activado y conectado*")
130|        else:
131|            logger.warning(f" Backend respondió: {test_response.status_code}")
132|    except Exception as e:
133|        logger.error(f" No se pudo verificar backend: {e}")
134|    
135|    port = int(os.environ.get('PORT', 8000))
136|    app.run(host='0.0.0.0', port=port, debug=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Error handler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_error_handler(error_handler)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Iniciar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(" Bot iniciado. Esperando mensajes...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run_polling(allowed_updates=Update.ALL_TYPES)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()
