"""
 CEREBRO AI - BOT DE TELEGRAM
Conecta directamente con el backend de Render
"""

import asyncio
import aiohttp
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
7|import os
8|import requests
9|import logging
10|from flask import Flask, request, jsonify
# Configuración
TELEGRAM_TOKEN = "7708509018:AAErAOblRAlC587j1QB4k19PAfDgoiZ3kWk"
TELEGRAM_CHAT_ID = 7202793910
CEREBRO_API = "https://ai-agent-backend80.onrender.com/api/agent"
BACKEND_URL = "https://ai-agent-backend80.onrender.com/api"
# Estado del bot
user_sessions = {}

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Comando /start"""
        user_id = update.effective_user.id
            user_sessions[user_id] = {"activo": True}
                
                    mensaje = """
                    🧠 **CEREBRO AI - Asistente personal**

                    ¡Hola! Soy tu asistente para gestionar tu Web.

                    **Comandos disponibles:**
                    /productos - Lista productos de la tienda
                    /crear - Crear nuevo producto
                    /pedidos - Ver últimos pedidos
                    /clientes - Estadísticas de clientes
                    /ayuda - Ver todos los comandos

                    También puedes escribirme directamente cualquier comando, por ejemplo:
                    • "Lista los últimos 5 productos"
                    • "Crea un producto llamado X"
                    • "¿Cuántos pedidos tengo hoy?"

                    ¡Pruébame! 
                    """
                        await update.message.reply_text(mensaje, parse_mode='Markdown')


                        async def ayuda(update: Update, context: ContextTypes.DEFAULT_TYPE):
                            """Comando /ayuda"""
                                mensaje = """
                                 **COMANDOS DE CEREBRO AI**

                                ** Productos:**
                                /productos - Lista productos
                                /crear - Crear producto
                                /stock - Ver stock bajo

                                ** Pedidos:**
                                /pedidos - Últimos pedidos
                                /ventas - Estadísticas de ventas

                                ** Clientes:**
                                /clientes - Info de clientes
                                /nuevos - Clientes nuevos

                                ** Analíticas:**
                                /dashboard - Dashboard completo
                                /ingresos - Ingresos del mes

                                ** Sistema:**
                                /status - Estado del backend
                                /ayuda - Este mensaje

                                ** Modo chat:**
                                También puedes hablarme naturalmente:
                                • "Muéstrame los productos más vendidos"
                                • "Crea un producto de prueba"
                                • "¿Cuánto he vendido hoy?"
                                """
                                    await update.message.reply_text(mensaje, parse_mode='Markdown')


                                    async def productos(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                        """Comando /productos"""
                                            await update.message.reply_text("🔍 Consultando productos...")
                                                respuesta = await ejecutar_comando("lista todos los productos de woocommerce", update.effective_user.id)
                                                    await update.message.reply_text(respuesta)


                                                    async def crear_producto(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                        """Comando /crear"""
                                                            if context.args:
                                                                    nombre = " ".join(context.args)
                                                                            await update.message.reply_text(f" Creando producto '{nombre}'...")
                                                                                    respuesta = await ejecutar_comando(f"crea un producto llamado {nombre}", update.effective_user.id)
                                                                                            await update.message.reply_text(respuesta)
                                                                                                else:
                                                                                                        await update.message.reply_text(" Uso: /crear [nombre del producto]")


                                                                                                        async def pedidos(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                            """Comando /pedidos"""
                                                                                                                await update.message.reply_text(" Consultando pedidos...")
                                                                                                                    respuesta = await ejecutar_comando("muestra los últimos 10 pedidos", update.effective_user.id)
                                                                                                                        await update.message.reply_text(respuesta)


                                                                                                                        async def status(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                            """Comando /status - Verifica estado del backend"""
                                                                                                                                await update.message.reply_text(" Verificando backend...")
                                                                                                                                    
                                                                                                                                        try:
                                                                                                                                                async with aiohttp.ClientSession() as session:
                                                                                                                                                            async with session.get(f"{CEREBRO_API}/status", timeout=10) as resp:
                                                                                                                                                                            if resp.status == 200:
                                                                                                                                                                                                data = await resp.json()
                                                                                                                                                                                                                    mensaje = f"""
                                                                                                                                                                                                                     **Backend operativo**

                                                                                                                                                                                                                     Estado: {data.get('status', 'OK')}
                                                                                                                                                                                                                     Agente: {'Activo' if data.get('agente_activo') else 'Inactivo'}
                                                                                                                                                                                                                     Base de datos: {'Conectada' if data.get('database_connected') else 'Desconectada'}
                                                                                                                                                                                                                     Modelo: {data.get('modelo', 'N/A')}
                                                                                                                                                                                                                     Conversaciones: {data.get('conversaciones_totales', 0)}
                                                                                                                                                                                                                     Herramientas: {data.get('herramientas_disponibles', 0)}
                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                        await update.message.reply_text(mensaje, parse_mode='Markdown')
                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                            await update.message.reply_text(f" Backend respondió con error: {resp.status}")
                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                        await update.message.reply_text(f" Error al conectar: {str(e)}")


                                                                                                                                                                                                                                                                                        async def ejecutar_comando(comando: str, user_id: int) -> str:
                                                                                                                                                                                                                                                                                            """Ejecuta un comando en el backend de Cerebro"""
                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                        async with aiohttp.ClientSession() as session:
                                                                                                                                                                                                                                                                                                                    payload = {
                                                                                                                                                                                                                                                                                                                                    "command": comando,
                                                                                                                                                                                                                                                                                                                                    # Comandos especiales
88|        if text in ['/start', '/ayuda', '/help']:
89|            send_telegram_message(
90|                " *Bot Cerebro AI - FIX URGENTE*\n\n"
91|                f" Backend: {BACKEND_URL}\n"
92|                f" Estado: Conectado y funcionando\n\n"
93|                "Envía cualquier mensaje para probar la conexión.",
94|                chat_id
95|            )
96|            return jsonify({"ok": True})
97|        
98|        # Procesar mensaje normal
99|        if text and not text.startswith('/'):
100|            logger.info(f" Procesando: {text}")
101|            
102|            # Llamar backend
103|            result = call_backend_agent(text, f"telegram_{chat_id}")
104|            
105|            if result['success']:
106|                mensaje = result.get('mensaje', 'Sin respuesta del backend')
107|                send_telegram_message(f" {mensaje}", chat_id)
108|                logger.info(" Enviado correctamente")
109|            else:
110|                error = result.get('error', 'Error desconocido')
111|                send_telegram_message(f" Error: {error}", chat_id)
112|                logger.error(f" Error: {error}")
113|        
114|        return jsonify({"ok": True})
115|        
116|    except Exception as e:
117|        logger.error(f" Error webhook: {e}")
118|        return jsonify({"ok": False, "error": str(e)}), 500
119|
120|if __name__ == "__main__":
121|    logger.info(" INICIANDO TELEGRAM BOT URGENTE")
122|    logger.info(f" Backend: {BACKEND_URL}")
                                                                                                                                                                                                                                                                                                                                                    "user_id": f"telegram_{user_id}"
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                        async with session.post(
                                                                                                                                                                                                                                                                                                                                                                                                        f"{CEREBRO_API}/execute",
                                                                                                                                                                                                                                                                                                                                                                                                                        json=payload,
                                                                                                                                                                                                                                                                                                                                                                                                                                        timeout=30
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) as resp:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if resp.status == 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data = await resp.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return data.get('mensaje') or data.get('message') or data.get('respuesta') or str(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error_text = await resp.text()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return f" Error {resp.status}: {error_text}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except asyncio.TimeoutError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "⏱ Timeout: El servidor tardó demasiado en responder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return f" Error de conexión: {str(e)}"


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def manejar_mensaje(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Maneja mensajes de texto normales"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user_id = update.effective_user.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        texto = update.message.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Indicador de que está procesando
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await update.message.reply_text(" Procesando...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Ejecutar comando
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                respuesta = await ejecutar_comando(texto, user_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Responder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await update.message.reply_text(respuesta)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Maneja errores"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f" Error: {context.error}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if update and update.message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await update.message.reply_text(f" Ocurrió un error: {context.error}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Inicia el bot"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(" Iniciando Cerebro AI Bot...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Crear aplicación
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app = Application.builder().token(TELEGRAM_TOKEN).build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Comandos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(CommandHandler("ayuda", ayuda))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.add_handler(CommandHandler("help", ayuda))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.add_handler(CommandHandler("productos", productos))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_handler(CommandHandler("crear", crear_producto))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(CommandHandler("pedidos", pedidos))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.add_handler(CommandHandler("status", status))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Mensajes de texto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, manejar_mensaje))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Procesar mensaje normal
99|        if text and not text.startswith('/'):
100|            logger.info(f" Procesando: {text}")
101|            
102|            # Llamar backend
103|            result = call_backend_agent(text, f"telegram_{chat_id}")
104|            
105|            if result['success']:
106|                mensaje = result.get('mensaje', 'Sin respuesta del backend')
107|                send_telegram_message(f" {mensaje}", chat_id)
108|                logger.info(" Enviado correctamente")
109|            else:
110|                error = result.get('error', 'Error desconocido')
111|                send_telegram_message(f" Error: {error}", chat_id)
112|                logger.error(f" Error: {error}")
113|        
114|        return jsonify({"ok": True})
115|        
116|    except Exception as e:
117|        logger.error(f" Error webhook: {e}")
118|        return jsonify({"ok": False, "error": str(e)}), 500
119|
120|if __name__ == "__main__":
121|    logger.info(" INICIANDO TELEGRAM BOT URGENTE")
122|    logger.info(f" Backend: {BACKEND_URL}")
123|    
124|    # Test inicial
125|    try:
126|        test_response = requests.get(f"https://ai-agent-backend80.onrender.com/api/agent/status", timeout=10)
127|        if test_response.status_code == 200:
128|            logger.info(" Backend verificado")
129|            send_telegram_message(" *Bot fix urgente activado y conectado*")
130|        else:
131|            logger.warning(f" Backend respondió: {test_response.status_code}")
132|    except Exception as e:
133|        logger.error(f" No se pudo verificar backend: {e}")
134|    
135|    port = int(os.environ.get('PORT', 8000))
136|    app.run(host='0.0.0.0', port=port, debug=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Error handler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_error_handler(error_handler)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Iniciar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(" Bot iniciado. Esperando mensajes...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run_polling(allowed_updates=Update.ALL_TYPES)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()
