import os
import aiohttp
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, ContextTypes, filters

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
BACKEND_URL = os.environ.get("BACKEND_URL")
user_vars = {}

async def setvar(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if len(context.args) < 2:
        await update.message.reply_text("Uso: /setvar clave valor")
        return
    key, value = context.args[0], " ".join(context.args[1:])
    user_vars[update.effective_user.id] = user_vars.get(update.effective_user.id, {})
    user_vars[update.effective_user.id][key] = value
    await update.message.reply_text(f"🔧 Variable '{key}' configurada como '{value}'.")

async def gestion(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    texto = update.message.text
    # Construye payload con variables personales para el backend
    payload = {
        "command": texto,
        "user_id": f"telegram_{user_id}",
        "vars": user_vars.get(user_id, {})
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(f"{BACKEND_URL}/agent/execute", json=payload, timeout=30) as resp:
            data = await resp.json()
            respuesta = data.get('mensaje') or str(data)
            await update.message.reply_text(respuesta)

def main():
    app = Application.builder().token(TELEGRAM_TOKEN).build()
    app.add_handler(CommandHandler("setvar", setvar))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, gestion))
    app.run_polling()

if __name__ == "__main__":
    main()

 from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
import aiohttp

app = FastAPI()

@app.post("/agent/execute")
async def execute_command(payload: dict):
    texto = payload.get("command", "").lower()
    user_vars = payload.get("vars", {})

    # Ejemplo de integración dinámica por variable
    if user_vars.get("endpoint_woo"):
        wc_url = user_vars.get("endpoint_woo")
        wc_resp = await get_external_saas(wc_url)
        return JSONResponse(content={"mensaje": f"Productos WooCommerce conectados a {wc_url}: {wc_resp}"})

    if user_vars.get("api_key_stripe"):
        stripe_key = user_vars.get("api_key_stripe")
        # Aquí podrías hacer llamada a Stripe usando stripe_key

    if user_vars.get("curso_api"):
        curso_url = user_vars.get("curso_api")
        cursos = await get_external_saas(curso_url)
        return JSONResponse(content={"mensaje": f"Cursos disponibles: {cursos}"})

    # Si no hay variables específicas, IA fallback
    ia_response = await get_perplexity_response(texto)
    return JSONResponse(content={"mensaje": ia_response})

async def get_external_saas(url, params=None):
    async with aiohttp.ClientSession() as session:
        async with session.get(url, params=params or {}, timeout=20) as resp:
            if resp.status == 200:
                return await resp.json()
            else:
                error = await resp.text()
                return {"error": error}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return data.get('mensaje') or data.get('message') or data.get('respuesta') or str(data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error_text = await resp.text()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return f" Error {resp.status}: {error_text}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except asyncio.TimeoutError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "⏱ Timeout: El servidor tardó demasiado en responder"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return f" Error de conexión: {str(e)}"


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def manejar_mensaje(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Maneja mensajes de texto normales"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user_id = update.effective_user.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        texto = update.message.text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Indicador de que está procesando
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await update.message.reply_text(" Procesando...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Ejecutar comando
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                respuesta = await ejecutar_comando(texto, user_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Responder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await update.message.reply_text(respuesta)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Maneja errores"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f" Error: {context.error}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if update and update.message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await update.message.reply_text(f" Ocurrió un error: {context.error}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Inicia el bot"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(" Iniciando Cerebro AI Bot...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Crear aplicación
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app = Application.builder().token(TELEGRAM_TOKEN).build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Comandos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(CommandHandler("ayuda", ayuda))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.add_handler(CommandHandler("help", ayuda))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.add_handler(CommandHandler("productos", productos))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_handler(CommandHandler("crear", crear_producto))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(CommandHandler("pedidos", pedidos))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.add_handler(CommandHandler("status", status))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Mensajes de texto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, manejar_mensaje))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Procesar mensaje normal
99|        if text and not text.startswith('/'):
100|            logger.info(f" Procesando: {text}")
101|            
102|            # Llamar backend
103|            result = call_backend_agent(text, f"telegram_{chat_id}")
104|            
105|            if result['success']:
106|                mensaje = result.get('mensaje', 'Sin respuesta del backend')
107|                send_telegram_message(f" {mensaje}", chat_id)
108|                logger.info(" Enviado correctamente")
109|            else:
110|                error = result.get('error', 'Error desconocido')
111|                send_telegram_message(f" Error: {error}", chat_id)
112|                logger.error(f" Error: {error}")
113|        
114|        return jsonify({"ok": True})
115|        
116|    except Exception as e:
117|        logger.error(f" Error webhook: {e}")
118|        return jsonify({"ok": False, "error": str(e)}), 500
119|
120|if __name__ == "__main__":
121|    logger.info(" INICIANDO TELEGRAM BOT URGENTE")
122|    logger.info(f" Backend: {BACKEND_URL}")
123|    
124|    # Test inicial
125|    try:
126|        test_response = requests.get(f"https://ai-agent-backend80.onrender.com/api/agent/status", timeout=10)
127|        if test_response.status_code == 200:
128|            logger.info(" Backend verificado")
129|            send_telegram_message(" *Bot fix urgente activado y conectado*")
130|        else:
131|            logger.warning(f" Backend respondió: {test_response.status_code}")
132|    except Exception as e:
133|        logger.error(f" No se pudo verificar backend: {e}")
134|    
135|    port = int(os.environ.get('PORT', 8000))
136|    app.run(host='0.0.0.0', port=port, debug=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Error handler
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.add_error_handler(error_handler)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Iniciar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(" Bot iniciado. Esperando mensajes...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run_polling(allowed_updates=Update.ALL_TYPES)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()
